Readaptação do jogo ao novo visual
evanbros/jogo-da-velha pull request #9
Opened 2017-11-12 04:02 UTC by tiagoevanp

Sincronização do novo visual do jogo com o seu funcionamento.

2017-11-13 12:53 UTC, tassoevan commented on jogo.js
> +    document.getElementById(touch).setAttribute("style", "display:none");
Boa! Mas padronize as strings com aspas simples em vez de duplas.

2017-11-13 12:56 UTC, tassoevan commented on jogo.js
> +  const criarHandlerParaMarcar = (i, j, touch) => function () {
O parâmetro `touch` é desnecessário. Como a `function` é usada como event listener, `this` vai fazer referência ao elemento que está ativando o evento. Por exemplo, se você adiciona um event listener a um elemento `xyz`, o valor de `this` é igual a `xyz` na função sendo chamada.

2017-11-13 12:57 UTC, tassoevan commented on jogo.js
> +  const click = [];
Talvez `click` não seja um bom nome, especialmente porque no futuro podemos usar eventos touch (mobile) para chamar as ações.

2017-11-13 12:58 UTC, tassoevan requested changes
Favor analisar todos os comentários feitos no código.

2017-11-14 01:20 UTC, tassoevan commented
![captura de tela de 2017-11-13 23-19-57](https://user-images.githubusercontent.com/2263066/32757960-37bcd1fa-c8c9-11e7-8a48-20aae24ed3eb.png)
É normal o balão estar vazio?

2017-11-25 19:55 UTC, tiagoevanp commented
Normal não, mas ainda não consegui criar uma resposta de forma adequada para vencedor e empate.

2017-11-25 19:56 UTC, tiagoevanp commented
Não entendi o pedido de analisar os comentários do arquivo.

2017-11-25 22:17 UTC, tassoevan approved these changes

2017-11-25 22:17 UTC, merged